import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import { Users, FileText, DollarSign, TrendingUp, CreditCard } from 'lucide-react'

const AdminDashboard = () => {
  const navigate = useNavigate()
  const [stats, setStats] = useState({
    totalDealers: 0,
    activeDealers: 0,
    totalReports: 0,
    totalRevenue: 0,
    tokensSold: 0,
    recentActivity: []
  })
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchDashboardStats()
  }, [])

  const fetchDashboardStats = async () => {
    setLoading(true)
    try {
      // Fetch dealers count
      const { count: totalDealers } = await supabase
        .from('profiles')
        .select('*', { count: 'exact', head: true })

      const { count: activeDealers } = await supabase
        .from('profiles')
        .select('*', { count: 'exact', head: true })
        .eq('status', 'active')

      // Fetch reports count
      const { count: totalReports } = await supabase
        .from('reports')
        .select('*', { count: 'exact', head: true })

      // Fetch revenue from payments
      const { data: payments } = await supabase
        .from('payments')
        .select('amount')
        .eq('status', 'completed')

      const totalRevenue = payments?.reduce((sum, p) => sum + (p.amount || 0), 0) || 0
      // Fetch tokens sold from token transactions
const { data: tokenTransactions } = await supabase
    .from('token_transactions')
    .select('amount')
    .eq('transaction_type', 'PURCHASE')

const tokensSold = tokenTransactions?.reduce((sum, t) => sum + (t.amount || 0), 0) || 0

      // Fetch recent activity
      const { data: recentActivity } = await supabase
        .from('activity_logs')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(5)

      setStats({
        totalDealers: totalDealers || 0,
        activeDealers: activeDealers || 0,
        totalReports: totalReports || 0,
        totalRevenue: totalRevenue,
        tokensSold: tokensSold,
        recentActivity: recentActivity || []
      })
    } catch (error) {
      console.error('Error fetching dashboard stats:', error)
    } finally {
      setLoading(false)
    }
  }

  const StatCard = ({ title, value, icon: Icon, subtitle }) => (
    <div className="bg-white border border-[#E5E5E5] rounded p-6">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-[#555555]">{title}</p>
          <p className="text-2xl font-bold text-[#111111] mt-1">{value}</p>
          {subtitle && <p className="text-xs text-[#555555] mt-1">{subtitle}</p>}
        </div>
        <Icon className="w-5 h-5 text-[#555555]" />
      </div>
    </div>
  )

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-8 h-8 border-2 border-[#111111] border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-[#111111]">Dashboard</h1>
        <p className="text-sm text-[#555555]">Overview of VectorDDK activity.</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <StatCard
          title="Total Dealers"
          value={stats.totalDealers}
          icon={Users}
          subtitle={`${stats.activeDealers} active`}
        />
        <StatCard
          title="Total Reports"
          value={stats.totalReports}
          icon={FileText}
          subtitle="Generated by dealers"
        />
        <StatCard
          title="Revenue"
          value={`KSh ${stats.totalRevenue.toLocaleString()}`}
          icon={DollarSign}
        />
        <StatCard
          title="Tokens Sold"
          value={stats.tokensSold}
          icon={CreditCard}
        />
      </div>

      <div className="grid lg:grid-cols-2 gap-4">
        <div className="bg-white border border-[#E5E5E5] rounded p-6">
          <h3 className="text-sm font-medium text-[#111111] mb-4">Recent Activity</h3>
          {stats.recentActivity.length > 0 ? (
            <div className="space-y-3">
              {stats.recentActivity.map((activity, index) => (
                <div key={index} className="flex items-start gap-3 pb-3 border-b border-[#E5E5E5] last:border-0">
                  <div className="w-2 h-2 mt-2 bg-[#111111] rounded-full flex-shrink-0" />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-[#111111]">{activity.action}</p>
                    <p className="text-xs text-[#555555]">
                      {new Date(activity.created_at).toLocaleString()}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-[#555555]">No recent activity</p>
          )}
        </div>

        <div className="bg-white border border-[#E5E5E5] rounded p-6">
          <h3 className="text-sm font-medium text-[#111111] mb-4">Quick Actions</h3>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={() => navigate('/admin/dealers')}
              className="p-4 text-left border border-[#E5E5E5] rounded hover:border-[#111111] transition-colors cursor-pointer"
            >
              <Users className="w-5 h-5 text-[#555555] mb-2" />
              <p className="text-sm font-medium text-[#111111]">View Dealers</p>
              <p className="text-xs text-[#555555]">Manage dealer accounts</p>
            </button>
            <button
              onClick={() => navigate('/admin/reports')}
              className="p-4 text-left border border-[#E5E5E5] rounded hover:border-[#111111] transition-colors cursor-pointer"
            >
              <FileText className="w-5 h-5 text-[#555555] mb-2" />
              <p className="text-sm font-medium text-[#111111]">View Reports</p>
              <p className="text-xs text-[#555555]">Check diagnostic reports</p>
            </button>
            <button
              onClick={() => navigate('/admin/token-packages')}
              className="p-4 text-left border border-[#E5E5E5] rounded hover:border-[#111111] transition-colors cursor-pointer"
            >
              <CreditCard className="w-5 h-5 text-[#555555] mb-2" />
              <p className="text-sm font-medium text-[#111111]">Manage Tokens</p>
              <p className="text-xs text-[#555555]">Token packages</p>
            </button>
            <button
              onClick={() => navigate('/admin/audit-log')}
              className="p-4 text-left border border-[#E5E5E5] rounded hover:border-[#111111] transition-colors cursor-pointer"
            >
              <TrendingUp className="w-5 h-5 text-[#555555] mb-2" />
              <p className="text-sm font-medium text-[#111111]">Audit Log</p>
              <p className="text-xs text-[#555555]">View system activity</p>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default AdminDashboard